#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


Gamma-Gamma_Serbo_Lecture01.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture01.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture01.1_04.09.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture01.2_04.09.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 01","NSU 2014")

Gamma-Gamma_Serbo_Lecture02.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture02.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture02.1_11.09.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture02.2_11.09.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 02","NSU 2014")

Gamma-Gamma_Serbo_Lecture03.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture03.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture03.1_18.09.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture03.2_18.09.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 03","NSU 2014")

Gamma-Gamma_Serbo_Lecture04.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture04.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture04.1_25.09.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture04.2_25.09.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 04","NSU 2014")

Gamma-Gamma_Serbo_Lecture05.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture05.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture05.1_02.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture05.2_02.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 05","NSU 2014")

Gamma-Gamma_Serbo_Lecture06.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture06.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture06.1_09.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture06.2_09.10.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 06","NSU 2014")

Gamma-Gamma_Serbo_Lecture07.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture07.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture07.1_16.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture07.2_16.10.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 07","NSU 2014")

Gamma-Gamma_Serbo_Lecture08.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture08.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture08.1_23.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture08.2_23.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 08","NSU 2014")

Gamma-Gamma_Serbo_Lecture09.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture09.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture09.1_30.10.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture09.2_30.10.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 09","NSU 2014")

Gamma-Gamma_Serbo_Lecture10.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture10.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture10.1_06.11.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture10.2_06.11.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 10","NSU 2014")

Gamma-Gamma_Serbo_Lecture11.$(VIDEOEXT): Gamma-Gamma_Serbo_Lecture11.png.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture11.1_13.11.2014.MTS.$(VIDEOEXT) Gamma-Gamma_Serbo_Lecture11.2_13.11.2014.MTS.$(VIDEOEXT)  Gamma-Gamma_Serbo_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Gamma-gamma Serbo V.G. Lecture N 11","NSU 2014")

# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

