#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


HEP_Serbo_Lecture01.$(VIDEOEXT): HEP_Serbo_Lecture01-1.png.$(VIDEOEXT) HEP_Serbo_Lecture01-2.png.$(VIDEOEXT) HEP_Serbo_Lecture01.1_13.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture01.2_13.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT) 
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 01","NSU 2013")

HEP_Serbo_Lecture02.$(VIDEOEXT): HEP_Serbo_Lecture02-1.png.$(VIDEOEXT) HEP_Serbo_Lecture02-2.png.$(VIDEOEXT) HEP_Serbo_Lecture02.1_13.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture02.2_13.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 02","NSU 2013")

HEP_Serbo_Lecture03.$(VIDEOEXT): HEP_Serbo_Lecture03-1.png.$(VIDEOEXT) HEP_Serbo_Lecture03-2.png.$(VIDEOEXT) HEP_Serbo_Lecture03.1_20.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture03.2_20.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture03.3_20.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 03","NSU 2013")

HEP_Serbo_Lecture04.$(VIDEOEXT): HEP_Serbo_Lecture04-1.png.$(VIDEOEXT) HEP_Serbo_Lecture04-2.png.$(VIDEOEXT) HEP_Serbo_Lecture04.1_27.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture04.2_27.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture04.3_27.09.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 04","NSU 2013")

HEP_Serbo_Lecture05.$(VIDEOEXT): HEP_Serbo_Lecture05-1.png.$(VIDEOEXT) HEP_Serbo_Lecture05-2.png.$(VIDEOEXT) HEP_Serbo_Lecture05.1_04.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture05.2_04.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 05","NSU 2013")

HEP_Serbo_Lecture06.$(VIDEOEXT): HEP_Serbo_Lecture06-1.png.$(VIDEOEXT) HEP_Serbo_Lecture06-2.png.$(VIDEOEXT) HEP_Serbo_Lecture06.1_10.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture06.2_10.10.2013.mts.$(VIDEOEXT)  HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 06","NSU 2013")

HEP_Serbo_Lecture07.$(VIDEOEXT): HEP_Serbo_Lecture07-1.png.$(VIDEOEXT) HEP_Serbo_Lecture07-2.png.$(VIDEOEXT) HEP_Serbo_Lecture07.1_18.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture07.2_18.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture07.3_18.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 07","NSU 2013")

HEP_Serbo_Lecture08.$(VIDEOEXT): HEP_Serbo_Lecture08-1.png.$(VIDEOEXT) HEP_Serbo_Lecture08-2.png.$(VIDEOEXT) HEP_Serbo_Lecture08.1_25.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture08.2_25.10.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords.png-1.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 08","NSU 2013")

HEP_Serbo_Lecture09.$(VIDEOEXT): HEP_Serbo_Lecture09-1.png.$(VIDEOEXT) HEP_Serbo_Lecture09-2.png.$(VIDEOEXT) HEP_Serbo_Lecture09.1_01.11.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture09.2_01.11.2013.mts.$(VIDEOEXT)  HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 09","NSU 2013")

HEP_Serbo_Lecture10.$(VIDEOEXT): HEP_Serbo_Lecture10-1.png.$(VIDEOEXT) HEP_Serbo_Lecture10-2.png.$(VIDEOEXT) HEP_Serbo_Lecture10.1_15.11.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture10.2_15.11.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 10","NSU 2013")

HEP_Serbo_Lecture11.$(VIDEOEXT): HEP_Serbo_Lecture11-1.png.$(VIDEOEXT) HEP_Serbo_Lecture11-2.png.$(VIDEOEXT) HEP_Serbo_Lecture11.1_15.11.2013.mts.$(VIDEOEXT)  HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 11","NSU 2013")

HEP_Serbo_Lecture12.$(VIDEOEXT): HEP_Serbo_Lecture12-1.png.$(VIDEOEXT) HEP_Serbo_Lecture12-2.png.$(VIDEOEXT) HEP_Serbo_Lecture12.1_22.11.2013.mts.$(VIDEOEXT)  HEP_Serbo_Lecture12.2_22.11.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 12","NSU 2013")

HEP_Serbo_Lecture13.$(VIDEOEXT): HEP_Serbo_Lecture13-1.png.$(VIDEOEXT) HEP_Serbo_Lecture13-2.png.$(VIDEOEXT) HEP_Serbo_Lecture13.1_29.11.2013.mts.$(VIDEOEXT)  HEP_Serbo_Lecture13.2_29.11.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 13","NSU 2013")

HEP_Serbo_Lecture14.$(VIDEOEXT): HEP_Serbo_Lecture14-1.png.$(VIDEOEXT) HEP_Serbo_Lecture14-2.png.$(VIDEOEXT) HEP_Serbo_Lecture14.1_06.12.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture14.2_06.12.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 14","NSU 2013")

HEP_Serbo_Lecture15.$(VIDEOEXT): HEP_Serbo_Lecture15-1.png.$(VIDEOEXT) HEP_Serbo_Lecture15-2.png.$(VIDEOEXT) HEP_Serbo_Lecture15.1_13.12.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture15.2_13.12.2013.mts.$(VIDEOEXT) HEP_Serbo_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Serbo V.G. Lecture N 15","NSU 2013")

# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

