#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"

History_of_Quantum_Theory_Grozin_Lecture01.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture01.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_01.1-13.09.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_01.2-13.09.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 01","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture02.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture02.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_02.1-20.09.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_02.2-20.09.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 02","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture03.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture03.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_03.1-27.09.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_03.2-27.09.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 03","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture04.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture04.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_04.1-04.10.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_04.2-04.10.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 04","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture05.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture05.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_05.1-11.10.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_05.2-11.10.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 05","NSU 2018")


History_of_Quantum_Theory_Grozin_Lecture06.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture06.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_06.1-18.10.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_06.2-18.10.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 06","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture07.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture07.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_07.1-25.10.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_07.2-25.10.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 07","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture08.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture08.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_08.1-01.11.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_08.2-01.11.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 08","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture09.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture09.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_09.1-08.11.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_09.2-08.11.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 09","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture10.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture10.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_10.1-15.11.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_10.2-15.11.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 10","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture11.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture11.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_11.1-22.11.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_11.2-22.11.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 11","NSU 2018")


History_of_Quantum_Theory_Grozin_Lecture12.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture12.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_12-29.11.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 12","NSU 2018")


History_of_Quantum_Theory_Grozin_Lecture13.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture13.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_13.1-06.12.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_13.2-06.12.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 13","NSU 2018")


History_of_Quantum_Theory_Grozin_Lecture14.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture14.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_14.1-13.12.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_14.2-13.12.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 14","NSU 2018")

History_of_Quantum_Theory_Grozin_Lecture15.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Lecture15.png.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_15.1-2-20.12.2018.MTS.$(VIDEOEXT) History_of_Quantum_Theory_Grozin_15.3-20.12.2018.MTS.$(VIDEOEXT)  History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin Lecture N 15","NSU 2018")

History_of_Quantum_Theory_Grozin_Seminar01.$(VIDEOEXT): History_of_Quantum_Theory_Grozin_Seminar01.png.$(VIDEOEXT) Grozin_Histiry_of_quantum_theory_seminar_18-02-2019.MTS.$(VIDEOEXT)   History_of_Quantum_Theory_Grozin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"History of Quantum Theory by Andrey Grozin BINP Seminar Part I","BINP 2019")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

