#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"

Reznichenko_Nonlinear_Channels.$(VIDEOEXT): Reznichenko_Nonlinear_Channels.png.$(VIDEOEXT) TO_Seminar_Reznichenko_Nonlinear_Channels_1_24.12.15.MTS.$(VIDEOEXT) TO_Seminar_Reznichenko_Nonlinear_Channels_2_24.12.15.MTS.$(VIDEOEXT) TO_Seminar_Reznichenko_Nonlinear_Channels_3_24.12.15.MTS.$(VIDEOEXT) Reznichenko_Nonlinear_Channels_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Alexey Reznichenko, Nonlinear Channels, 24.12.2015","BINP 2015")

Kozlov_Pentagon.$(VIDEOEXT): Kozlov_Pentagon.png.$(VIDEOEXT) TO_Seminar_Kozlov_Pentagon_17.12.15.MTS.$(VIDEOEXT)  Kozlov_Pentagon_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Mihail Kozlov, Diagramma Pentagon, 17.12.2015","BINP 2015")

Shepelyansky_Dynamical_thermalization_in_finite_quantum_systems.$(VIDEOEXT): Shepelyansky_Dynamical_thermalization_in_finite_quantum_systems.png.$(VIDEOEXT) Shepelyansky_Dynamical_thermalization_in_finite_quantum_systems_1_15.10.15.MTS.$(VIDEOEXT) Shepelyansky_Dynamical_thermalization_in_finite_quantum_systems_2_15.10.15.MTS.$(VIDEOEXT) Shepelyansky_Dynamical_thermalization_in_finite_quantum_systems_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"D. Shepelyansky, Dynamical thermalization in finite interacting systems, 15.10.2015","BINP 2015")

Kharkov_Spin-charge_separation.$(VIDEOEXT): Kharkov_Spin-charge_separation.png.$(VIDEOEXT) Kharkov_Spin-charge_separation_16.07.15-1.MTS.$(VIDEOEXT) Kharkov_Spin-charge_separation_16.07.15-2.MTS.$(VIDEOEXT) Kharkov_Spin-charge_separation_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Yaroslav Kharkov, Spin-charge separation: impurity induced magnetization in the vicinity of quantum critical point, 16.07.2015","BINP 2015")


Grozin_3Loop_Cusp_Anomalous_dimension_in_QCD.$(VIDEOEXT): Grozin_3Loop_Cusp_Anomalous_dimension_in_QCD.png.$(VIDEOEXT) Grozin_3Loop_Cusp_Anomalous_dimension_in_QCD1-12.3.15.MTS.$(VIDEOEXT) Grozin_3Loop_Cusp_Anomalous_dimension_in_QCD2-12.3.15.MTS.$(VIDEOEXT) Grozin_3Loop_Cusp_Anomalous_dimension_in_QCD_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Grozin A.G. Three-loop cusp anomalous dimension in QCD","BINP 2015")

Morokuma_Tominaga_Rapid_Transient_Phenomena_Discovered_in_Wide_Field_Surveys.$(VIDEOEXT): Morokuma_Tominaga_Rapid_Transient_Phenomena_Discovered_in_Wide_Field_Surveys.png.$(VIDEOEXT) Morokuma_Tominaga_Rapid_Transient_Phenomena_Discovered_in_Wide_Field_Surveys1-11.03.15.MTS.$(VIDEOEXT) Morokuma_Tominaga_Rapid_Transient_Phenomena_Discovered_in_Wide_Field_Surveys2-11.03.15.MTS.$(VIDEOEXT) Morokuma_Tominaga_Rapid_Transient_Phenomena_Discovered_in_Wide_Field_Surveys_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Tomoki Morokuma and Nozomu Tominaga Rapid Transient Phenomena Discovered in Wide-Field Surveys","BINP 2015")

Lee_Reducing_differential_equations_for_master_integrals_to_canonical_form.$(VIDEOEXT): Lee_Reducing_differential_equations_for_master_integrals_to_canonical_form.png.$(VIDEOEXT) Lee_Reducing_differential_equations_for_master_integrals_to_canonical_form_1_5.3.15.MTS.$(VIDEOEXT) Lee_Reducing_differential_equations_for_master_integrals_to_canonical_form_2_5.3.15.MTS.$(VIDEOEXT) Lee_Reducing_differential_equations_for_master_integrals_to_canonical_form_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Roman N. Lee Reducing differential equations for master integrals to canonical form","BINP 2015")

Shepelyansky_Google_Matrix_of_World_Trade_Network.$(VIDEOEXT): Shepelyansky_Google_Matrix_of_World_Trade_Network.png.$(VIDEOEXT) Shepelyansky_Google_Matrix_of_World_Trade_Network_1_18-12-14.MTS.$(VIDEOEXT) Shepelyansky_Google_Matrix_of_World_Trade_Network_2_18-12-14.MTS.$(VIDEOEXT) Shepelyansky_Google_Matrix_of_World_Trade_Network_3_18-12-14.MTS.$(VIDEOEXT) Shepelyansky_Google_Matrix_of_World_Trade_Network_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Dima Shepelyansky Google matrix of world trade nerwork","BINP 2014")


Dolgov_Problems_of_Cosmology_and_Particle_Physics01.$(VIDEOEXT): Dolgov_Problems_of_Cosmology_and_Particle_Physics01.png.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics1.1_9.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics1.2_9.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics1.3_9.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Alexandr Dolgov Cosmology and particle physics (part 1)","BINP 2014")

Dolgov_Problems_of_Cosmology_and_Particle_Physics02.$(VIDEOEXT): Dolgov_Problems_of_Cosmology_and_Particle_Physics02.png.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics2.1_10.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics2.2_10.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics2.3_10.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics2.4_10.12.14.MTS.$(VIDEOEXT) Dolgov_Problems_of_Cosmology_and_Particle_Physics_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Alexandr Dolgov, Cosmology and particle physics (part 2)","BINP 2014")


Potashov_SupernovaII_as_ruler.$(VIDEOEXT): Potashov_SupernovaII_as_ruler.png.$(VIDEOEXT) TO_Seminar_PotashovMSh.1_04_12_14.MTS.$(VIDEOEXT) TO_Seminar_PotashovMSh.2_04_12_14.MTS.$(VIDEOEXT) TO_Seminar_PotashovMSh.3_04_12_14.MTS.$(VIDEOEXT) Potashov_SupernovaII_as_ruler_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Marat Potashov Supernova type II as a ruler","BINP 2014")


Blinnikov_Supernova_HighLum.$(VIDEOEXT): Blinnikov_Supernova_HighLum.png.$(VIDEOEXT) TO_Seminar_BlinnikovSI.1_03_12_14.MTS.$(VIDEOEXT) TO_Seminar_BlinnikovSI.2_03_12_14.MTS.$(VIDEOEXT) TO_Seminar_BlinnikovSI.3_03_12_14.MTS.$(VIDEOEXT) Blinnikov_Supernova_HighLum_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Sergey Blinnikov Supernova HighLum","BINP 2014")


Glazyrin_Combustion_physics_in_1a_supernovas.$(VIDEOEXT): Glazyrin_Combustion_physics_in_1a_supernovas.png.$(VIDEOEXT) TO_Seminar_Glazyrin_Combustion_physics_in_1a_supernovas-1_2.12.2014.mts.$(VIDEOEXT) TO_Seminar_Glazyrin_Combustion_physics_in_1a_supernovas-2_2.12.2014.mts.$(VIDEOEXT) Glazyrin_Combustion_physics_in_1a_supernovas_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Semen Glazyrin, Combustion physics in 1a supernovas","BINP 2014")

Yudin_AsroPhStars01.$(VIDEOEXT): Yudin_AsroPhStars01.png.$(VIDEOEXT) TO_Seminar_Judin_01.1_26-11-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_01.2_26-11-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_01.3_26-11-2014.MTS.$(VIDEOEXT) Yudin_AsroPhStars_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Andrej Yudin Quick Start introduction to astrophysics of stars (part 1)","BINP 2014")


Yudin_AsroPhStars02.$(VIDEOEXT): Yudin_AsroPhStars02.png.$(VIDEOEXT) TO_Seminar_Judin_02.1_27-11-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_02.2_27-11-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_02.3_27-11-2014.MTS.$(VIDEOEXT) Yudin_AsroPhStars_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Andrej Yudin Quick Start introduction to astrophysics of stars (part 2)","BINP 2014")

Yudin_Core-collapse_supernovae_and_neutron_stars.$(VIDEOEXT): Yudin_Core-collapse_supernovae_and_neutron_stars.png.$(VIDEOEXT) TO_Seminar_Judin_03.1_01-12-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_03.2_01-12-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_03.3_01-12-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_03.4_01-12-2014.MTS.$(VIDEOEXT) TO_Seminar_Judin_03.5_01-12-2014.MTS.$(VIDEOEXT) Yudin_Core-collapse_supernovae_and_neutron_stars_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Andrej Yudin Core-collapse supernovae and neutron stars","BINP 2014")

Parnachev_Quantum_Entanglement_in_field_theories.$(VIDEOEXT): Parnachev_Quantum_Entanglement_in_field_theories.png.$(VIDEOEXT) Parnachev_Quantum_Entanglement_in_field_theories-1-29-05-14.mts.$(VIDEOEXT) Parnachev_Quantum_Entanglement_in_field_theories-2-29-05-14.mts.$(VIDEOEXT) Parnachev_Quantum_Entanglement_in_field_theories_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"A. Parnachev Quantum entanglement in field theories","BINP 2014")


Gorsky_Barion_as_Dyon_Instanton.$(VIDEOEXT): Gorsky_Barion_as_Dyon_Instanton.png.$(VIDEOEXT) Gorsky_Barion_as_Dyon_Instanton-1-28-05-2014.mts.$(VIDEOEXT) Gorsky_Barion_as_Dyon_Instanton-2-28-05-2014.mts.$(VIDEOEXT) Gorsky_Barion_as_Dyon_Instanton_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Alexandr Gorsky Baryon as Dionic Instanton","BINP 2014")


Gelash-Nonlinear_Stage_of_modulational_instability.$(VIDEOEXT): Gelash-Nonlinear_Stage_of_modulational_instability.png.$(VIDEOEXT) Gelash-Nonlinear_Stage_of_modulational_instability-22-05-2014-1.mts.$(VIDEOEXT) Gelash-Nonlinear_Stage_of_modulational_instability-22-05-2014-2.mts.$(VIDEOEXT) Gelash-Nonlinear_Stage_of_modulational_instability_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Andrey Gelash, Nonlinear Stage of modulational instability","BINP 2014")



# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)




