#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


Grabovsky_Theory_Of_Strong_Interactions_Lecture01.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture01.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_01_05.02.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 01","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture02.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture02.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_02_19.02.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 02","NSU 2020")


Grabovsky_Theory_Of_Strong_Interactions_Lecture03.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture03.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_03_20.02.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 03","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture04.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture04.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_04_26.02.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 04","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture05.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture05.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_05_04.03.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 05","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture06.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture06.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_06_11.03.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 06","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture07.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture07.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_07_18.03.20.mts.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 07","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture08.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture08.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_08_19.03.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 08","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture09.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture09.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_09_01.04.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 09","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture10.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture10.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_10_02.04.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 10","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture11.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture11.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_11_08.04.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 11","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture12.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture12.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_12_15.04.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 12","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture13.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture13.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_13_22.04.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 13","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture14.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture14.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_14_29.04.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 14","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture15.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture15.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_15.1_06.05.20.MTS.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_15.2_08.05.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 15","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture16.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture16.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_16_13.05.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 16","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture17.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture17.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_17-1_20.05.20.MTS.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_17-2_20.05.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 17","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture18.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture18.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_18_27.05.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 18","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture19.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture19.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_19.1_04.06.20.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 19","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture20.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture20.png.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_19.2_04.06.20-part1.MTS.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_19.2_04.06.20-part2.MTS.$(VIDEOEXT) Gabovsky_TheoryOfStrongInteractions_19.3_04.06.20-part1.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 20","NSU 2020")

Grabovsky_Theory_Of_Strong_Interactions_Lecture21.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture21.png.$(VIDEOEXT) QCD-Grabovsky-1-14.10.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 21","NSU 2024")

Grabovsky_Theory_Of_Strong_Interactions_Lecture22.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture22.png.$(VIDEOEXT) QCD-Grabovsky-2-21.10.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 22","NSU 2024")

Grabovsky_Theory_Of_Strong_Interactions_Lecture23.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture23.png.$(VIDEOEXT) QCD-Grabovsky-3-28.10.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 23","NSU 2024")

Grabovsky_Theory_Of_Strong_Interactions_Lecture24.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture24.png.$(VIDEOEXT) QCD-Grabovsky-4-11.11.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 24","NSU 2024")

Grabovsky_Theory_Of_Strong_Interactions_Lecture25.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture25.png.$(VIDEOEXT) QCD-Grabovsky-5-18.11.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 25","NSU 2024")

Grabovsky_Theory_Of_Strong_Interactions_Lecture26.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture26.png.$(VIDEOEXT) QCD-Grabovsky-6-25.11.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 26","NSU 2024")

Grabovsky_Theory_Of_Strong_Interactions_Lecture27.$(VIDEOEXT): Grabovsky_Theory_Of_Strong_Interactions_Lecture27.png.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture27-summery.png.$(VIDEOEXT) QCD-Grabovsky-7-02.12.24.MTS.$(VIDEOEXT) Grabovsky_Theory_Of_Strong_Interactions_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Theory of Strong Interactions by Andrey Grabovsky Lecture N 27","NSU 2024")



# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)
















