#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


HEP_Skovpen_Seminar01.$(VIDEOEXT): HEP_Skovpen_Seminar01.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_01.1-05-09-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_01.2-05-09-2014.MTS.$(VIDEOEXT) HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 01","NSU 2014")

HEP_Skovpen_Seminar02.$(VIDEOEXT): HEP_Skovpen_Seminar02.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.1-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.2-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.3-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.4-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.5-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.6-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.7-12-09-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_02.8-12-09-2014.mts.$(VIDEOEXT) HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 02","NSU 2014")

HEP_Skovpen_Seminar03.$(VIDEOEXT): HEP_Skovpen_Seminar03.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_03.1-19-09-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_03.2-19-09-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 03","NSU 2014")

HEP_Skovpen_Seminar04.$(VIDEOEXT): HEP_Skovpen_Seminar04.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_04.1-26-09-2014.MTS.$(VIDEOEXT)  Introduction_to_HEP_Seminars_Skovpen_04.2-26-09-2014.MTS.$(VIDEOEXT) HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 04","NSU 2014")

HEP_Skovpen_Seminar05.$(VIDEOEXT): HEP_Skovpen_Seminar05.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_05.1-03-10-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_05.2-03-10-2014.MTS.$(VIDEOEXT) HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 05","NSU 2014")

HEP_Skovpen_Seminar06.$(VIDEOEXT): HEP_Skovpen_Seminar06.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_06.1-10-10-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_06.2-10-10-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 06","NSU 2014")

HEP_Skovpen_Seminar07.$(VIDEOEXT): HEP_Skovpen_Seminar07.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_07.1-17-10-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_07.2-17-10-2014.mts.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_07.3-17-10-2014.MTS.$(VIDEOEXT) HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 07","NSU 2014")

HEP_Skovpen_Seminar08.$(VIDEOEXT): HEP_Skovpen_Seminar08.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_08.1-24-10-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_08.2-24-10-2014.MTS.$(VIDEOEXT) HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 08","NSU 2014")

HEP_Skovpen_Seminar09.$(VIDEOEXT): HEP_Skovpen_Seminar09.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_09.1-31-10-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_09.2-31-10-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 09","NSU 2014")

HEP_Skovpen_Seminar10.$(VIDEOEXT): HEP_Skovpen_Seminar10.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_10.1-07-11-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_10.2-07-11-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 10","NSU 2014")

HEP_Skovpen_Seminar11.$(VIDEOEXT): HEP_Skovpen_Seminar11.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_11.1-13-11-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_11.2-13-11-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 11","NSU 2014")

HEP_Skovpen_Seminar12.$(VIDEOEXT): HEP_Skovpen_Seminar12.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_12.1-14-11-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_12.2-14-11-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 12","NSU 2014")

HEP_Skovpen_Seminar13.$(VIDEOEXT): HEP_Skovpen_Seminar13.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_13.1-20-11-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_13.2-20-11-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 13","NSU 2014")

HEP_Skovpen_Seminar14.$(VIDEOEXT): HEP_Skovpen_Seminar14.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_14.1-21-11-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_14.2-21-11-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 14","NSU 2014")

HEP_Skovpen_Seminar15.$(VIDEOEXT): HEP_Skovpen_Seminar15.png.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_15.1-21-11-2014.MTS.$(VIDEOEXT) Introduction_to_HEP_Seminars_Skovpen_15.2-21-11-2014.MTS.$(VIDEOEXT)  HEP_Skovpen_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"HEP Skovpen Yu.I. Seminar N 15","NSU 2015")

# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

