#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


RGeom_Malkovich_Lecture01.$(VIDEOEXT): RGeom_Malkovich_Lecture01.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_1-1_17.10.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_1-2_17.10.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 01","NSU 2016")


RGeom_Malkovich_Lecture02.$(VIDEOEXT): RGeom_Malkovich_Lecture02.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_2_24.10.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 02","NSU 2016")


RGeom_Malkovich_Lecture03.$(VIDEOEXT): RGeom_Malkovich_Lecture03.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_3-1_31.10.2016.MTS.$(VIDEOEXT)  Riemannian_Geometry_Malkovich_3-2_31.10.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 03","NSU 2016")


RGeom_Malkovich_Lecture04.$(VIDEOEXT): RGeom_Malkovich_Lecture04.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_4.1_07.11.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_4.2_07.11.2016.MTS.$(VIDEOEXT)  RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 04","NSU 2016")

RGeom_Malkovich_Lecture05.$(VIDEOEXT): RGeom_Malkovich_Lecture05.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_5-1_14.11.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_5-2_14.11.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 05","NSU 2016")

RGeom_Malkovich_Lecture06.$(VIDEOEXT): RGeom_Malkovich_Lecture06.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_6-1_21.11.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_6-2_21.11.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 06","NSU 2016")

RGeom_Malkovich_Lecture07.$(VIDEOEXT): RGeom_Malkovich_Lecture07.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_7.1_05.12.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_7.2_05.12.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 07","NSU 2016")

RGeom_Malkovich_Lecture08.$(VIDEOEXT): RGeom_Malkovich_Lecture08.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_8.1_12.12.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_8.2_12.12.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 08","NSU 2016")

RGeom_Malkovich_Lecture09.$(VIDEOEXT): RGeom_Malkovich_Lecture09.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_9.1_19.12.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_9.2_19.12.2016.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 09","NSU 2016")

RGeom_Malkovich_Lecture10.$(VIDEOEXT): RGeom_Malkovich_Lecture10.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_10.1_26.12.2016.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_10.2_26.12.2016.mts.$(VIDEOEXT) Riemannian_Geometry_Malkovich_10.3_26.12.2016.mts.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 10","NSU 2016")

RGeom_Malkovich_Lecture11.$(VIDEOEXT): RGeom_Malkovich_Lecture11.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_11.1_27.01.2017.mts.$(VIDEOEXT) Riemannian_Geometry_Malkovich_11.2_27.01.2017.mts.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 11","NSU 2016")

RGeom_Malkovich_Lecture12.$(VIDEOEXT): RGeom_Malkovich_Lecture12.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_12.1_03.02.2017.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_12.2_03.02.2017.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 12","NSU 2016")

RGeom_Malkovich_Lecture13.$(VIDEOEXT): RGeom_Malkovich_Lecture13.png.$(VIDEOEXT) Riemannian_Geometry_Malkovich_13.1_10.02.2017.MTS.$(VIDEOEXT) Riemannian_Geometry_Malkovich_13.2_10.02.2017.MTS.$(VIDEOEXT) RGeom_Malkovich_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"RGeom Evgeny Malkovich Lecture 13","NSU 2016")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

