#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"

# Lectures 2022

GR-dop-glavy_Grabovsky_Lecture01.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture01.png.$(VIDEOEXT) Grabovsky-dop-GR-1-1-14.9.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-1-2-14.9.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 01","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture02.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture02.png.$(VIDEOEXT) Grabovsky-dop-GR-2-1-26.9.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-2-2-21.9.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 02","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture03.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture03.png.$(VIDEOEXT) Grabovsky-dop-GR-3-1-28.9.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-3-2-28.9.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 03","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture04.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture04.png.$(VIDEOEXT) Grabovsky-dop-GR-4-1-5.10.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-4-2-5.10.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 04","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture05.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture05.png.$(VIDEOEXT) GR-dop-glavy_Grabovsky_Lecture05-summery.png.$(VIDEOEXT) Grabovsky-dop-GR-5-1-13.10.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-5-2-12.10.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 05","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture06.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture06.png.$(VIDEOEXT) GR-dop-glavy_Grabovsky_Lecture06-summery.png.$(VIDEOEXT) Grabovsky-dop-GR-6-1-19.10.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-6-2-19.10.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 06","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture07.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture07.png.$(VIDEOEXT) Grabovsky-dop-GR-7-1-26.10.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-7-2-26.10.22.MTS.$(VIDEOEXT)  GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 07","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture08.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture08.png.$(VIDEOEXT) Grabovsky-dop-GR-8-1-2.11.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-8-2-2.11.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 08","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture09.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture09.png.$(VIDEOEXT) Grabovsky-dop-GR-9-1-9.11.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-9-2-9.11.22.MTS.$(VIDEOEXT)  GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 09","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture10.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture10.png.$(VIDEOEXT) Grabovsky-dop-GR-10-1-16.11.22.MTS.$(VIDEOEXT) Grabovsky-dop-GR-10-2-16.11.22.MTS.$(VIDEOEXT)  GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 10","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture11.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture11.png.$(VIDEOEXT) GR-dop-glavy_Grabovsky_Lecture11-summery.png.$(VIDEOEXT) Grabovsky-dop-GR-11-1-2-23.11.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 11","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture12.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture12.png.$(VIDEOEXT) Grabovsky-dop-GR-12-1-2-30.11.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 12","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture13.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture13.png.$(VIDEOEXT) Grabovsky-dop-GR-13-1-2-7.12.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 13","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture14.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture14.png.$(VIDEOEXT) Grabovsky-dop-GR-14-1-2-14.12.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 14","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture15.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture15.png.$(VIDEOEXT) Grabovsky-dop-GR-15-1-2-21.12.22.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 15","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture16.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture16.png.$(VIDEOEXT) Grabovsky-dop-GR-16-1-2-20.2.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 16","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture17.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture17.png.$(VIDEOEXT) Grabovsky-dop-GR-17-1-1.3.23.MTS.$(VIDEOEXT) Grabovsky-dop-GR-17-2-1.3.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 17","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture18.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture18.png.$(VIDEOEXT) Grabovsky-dop-GR-18-1-15.3.23.MTS.$(VIDEOEXT) Grabovsky-dop-GR-18-2-15.3.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 18","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture19.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture19.png.$(VIDEOEXT) Grabovsky-dop-GR-19-1-22.3.23.MTS.$(VIDEOEXT) Grabovsky-dop-GR-19-2-22.3.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 19","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture20.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture20.png.$(VIDEOEXT) Grabovsky-dop-GR-20-1-2-29.3.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 20","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture21.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture21.png.$(VIDEOEXT) Grabovsky-dop-GR-21-1-2-5.4.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 21","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture22.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture22.png.$(VIDEOEXT) Grabovsky-dop-GR-22-1-2-12.4.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 22","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture23.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture23.png.$(VIDEOEXT) Grabovsky-dop-GR-23-1-2-19.4.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 23","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture24.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture24.png.$(VIDEOEXT) Grabovsky-dop-GR-24-1-2-26.4.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 24","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture25.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture25.png.$(VIDEOEXT) Grabovsky-dop-GR-25-1-2-3.5.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 25","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture26.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture26.png.$(VIDEOEXT) Grabovsky-dop-GR-26-1-2-10.5.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 26","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture27.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture27.png.$(VIDEOEXT) Grabovsky-dop-GR-27-1-2-17.5.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 27","NSU 2022")

GR-dop-glavy_Grabovsky_Lecture28.$(VIDEOEXT): GR-dop-glavy_Grabovsky_Lecture28.png.$(VIDEOEXT) Grabovsky-dop-GR-28-1-2-24.5.23.MTS.$(VIDEOEXT) GR-dop-glavy_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity additional chapters Andrei Grabovsky Lecture N 28","NSU 2022")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

