#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


QCD_Fadin_Lecture01.$(VIDEOEXT): QCD_Fadin_Lecture01.png.$(VIDEOEXT) QCD_Fadin_Lecture01.1_18.02.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture01.2_18.02.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 01","NSU 2014")

QCD_Fadin_Lecture02.$(VIDEOEXT): QCD_Fadin_Lecture02.png.$(VIDEOEXT) QCD_Fadin_Lecture02.1_18.02.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 02","NSU 2014")

QCD_Fadin_Lecture03.$(VIDEOEXT): QCD_Fadin_Lecture03.png.$(VIDEOEXT) QCD_Fadin_Lecture03.1_20.02.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture03.2_20.02.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 03","NSU 2014")

QCD_Fadin_Lecture04.$(VIDEOEXT): QCD_Fadin_Lecture04.png.$(VIDEOEXT) QCD_Fadin_Lecture04.1_11.03.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 04","NSU 2014")

QCD_Fadin_Lecture05.$(VIDEOEXT): QCD_Fadin_Lecture05.png.$(VIDEOEXT) QCD_Fadin_Lecture05.1_18.03.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 05","NSU 2014")

QCD_Fadin_Lecture06.$(VIDEOEXT): QCD_Fadin_Lecture06.png.$(VIDEOEXT) QCD_Fadin_Lecture06.1_25.03.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture06.2_25.03.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 06","NSU 2014")

QCD_Fadin_Lecture07.$(VIDEOEXT): QCD_Fadin_Lecture07.png.$(VIDEOEXT) QCD_Fadin_Lecture07.1_01.04.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture07.2_01.04.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 07","NSU 2014")

QCD_Fadin_Lecture08.$(VIDEOEXT): QCD_Fadin_Lecture08.png.$(VIDEOEXT) QCD_Fadin_Lecture08.1_08.04.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 08","NSU 2014")

QCD_Fadin_Lecture09.$(VIDEOEXT): QCD_Fadin_Lecture09.png.$(VIDEOEXT) QCD_Fadin_Lecture09.1_15.04.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture09.2_15.04.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 09","NSU 2014")

QCD_Fadin_Lecture10.$(VIDEOEXT): QCD_Fadin_Lecture10.png.$(VIDEOEXT) QCD_Fadin_Lecture10.1_15.04.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 10","NSU 2014")

QCD_Fadin_Lecture11.$(VIDEOEXT): QCD_Fadin_Lecture11.png.$(VIDEOEXT) QCD_Fadin_Lecture11.1_22.04.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture11.2_22.04.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 11","NSU 2014")

QCD_Fadin_Lecture12.$(VIDEOEXT): QCD_Fadin_Lecture12.png.$(VIDEOEXT) QCD_Fadin_Lecture12.1_29.04.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture12.2_29.04.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 12","NSU 2014")

QCD_Fadin_Lecture13.$(VIDEOEXT): QCD_Fadin_Lecture13.png.$(VIDEOEXT) QCD_Fadin_Lecture13.1_06.05.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture13.2_06.05.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 13","NSU 2014")

QCD_Fadin_Lecture14.$(VIDEOEXT): QCD_Fadin_Lecture14.png.$(VIDEOEXT) QCD_Fadin_Lecture14.1_13.05.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 14","NSU 2014")

QCD_Fadin_Lecture15.$(VIDEOEXT): QCD_Fadin_Lecture15.png.$(VIDEOEXT) QCD_Fadin_Lecture15.1_27.05.2014.mts.$(VIDEOEXT) QCD_Fadin_Lecture15.2_27.05.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 15","NSU 2014")

QCD_Fadin_Lecture16.$(VIDEOEXT): QCD_Fadin_Lecture16.png.$(VIDEOEXT) QCD_Fadin_Lecture16.1_11.04.2014.mts.$(VIDEOEXT)  QCD_Fadin_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Fadin V.S. Lecture N 16","NSU 2014")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

