#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"

Semihard_processes_Grabovsky_Lecture01.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture01.png.$(VIDEOEXT) Grabovsky_Semihard_processes_1-1_22.02.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_1-2_22.02.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 01","NSU 2018")

Semihard_processes_Grabovsky_Lecture02.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture02.png.$(VIDEOEXT) Grabovsky_Semihard_processes_2-1_02.03.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_2-2_02.03.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 02","NSU 2018")

Semihard_processes_Grabovsky_Lecture03.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture03.png.$(VIDEOEXT) Grabovsky_Semihard_processes_3-1-_16.03.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_3-3-16.03.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 03","NSU 2018")

Semihard_processes_Grabovsky_Lecture04.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture04.png.$(VIDEOEXT) Grabovsky_Semihard_processes_4-1_23.03.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_4-2_23.03.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 04","NSU 2018")

Semihard_processes_Grabovsky_Lecture05.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture05.png.$(VIDEOEXT) Grabovsky_Semihard_processes_5-1_30.03.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_5-2_30.03.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 05","NSU 2018")

Semihard_processes_Grabovsky_Lecture06.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture06.png.$(VIDEOEXT) Grabovsky_Semihard_processes_6-1_06.04.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_6-2_06.04.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_6-3_06.04.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 06","NSU 2018")

Semihard_processes_Grabovsky_Lecture07.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture07.png.$(VIDEOEXT) Grabovsky_Semihard_processes_7-1_13.04.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_7-2_13.04.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 07","NSU 2018")

Semihard_processes_Grabovsky_Lecture08.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture08.png.$(VIDEOEXT) Grabovsky_Semihard_processes_8-1_20.04.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_8-2_20.04.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 08","NSU 2018")

Semihard_processes_Grabovsky_Lecture09.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture09.png.$(VIDEOEXT) Grabovsky_Semihard_processes_9-1_27.04.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_9-2_27.04.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 09","NSU 2018")

Semihard_processes_Grabovsky_Lecture10.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture10.png.$(VIDEOEXT) Grabovsky_Semihard_processes_10-1_4.05.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_10-2_4.05.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_10-3_4.05.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 10","NSU 2018")

Semihard_processes_Grabovsky_Lecture11.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture11.png.$(VIDEOEXT) Grabovsky_Semihard_processes_11-1_11.05.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_11-2_11.05.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_11-3_11.05.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 11","NSU 2018")

Semihard_processes_Grabovsky_Lecture12.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture12.png.$(VIDEOEXT) Grabovsky_Semihard_processes_12-1_18.05.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_12-2_18.05.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 12","NSU 2018")

Semihard_processes_Grabovsky_Lecture13.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture13.png.$(VIDEOEXT) Grabovsky_Semihard_processes_13-1_25.05.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_13-2_25.05.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 13","NSU 2018")

Semihard_processes_Grabovsky_Lecture14.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture14.png.$(VIDEOEXT) Grabovsky_Semihard_processes_14-1_01.06.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_14-2_01.06.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 14","NSU 2018")

Semihard_processes_Grabovsky_Lecture15.$(VIDEOEXT): Semihard_processes_Grabovsky_Lecture15.png.$(VIDEOEXT) Grabovsky_Semihard_processes_15-1_08.06.18.MTS.$(VIDEOEXT) Grabovsky_Semihard_processes_15-2_08.06.18.MTS.$(VIDEOEXT) Semihard_processes_Grabovsky_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Semihard processes by Andrey Grabovsky Lecture N 15","NSU 2018")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

