#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


Nucleus_Dmitriev_Lecture01.$(VIDEOEXT): Nucleus_Dmitriev_Lecture01.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture01.1-04-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture01.2-04-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 01","NSU 2014")

Nucleus_Dmitriev_Lecture02.$(VIDEOEXT): Nucleus_Dmitriev_Lecture02.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture02.1-11-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture02.2-11-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 02","NSU 2014")

Nucleus_Dmitriev_Lecture03.$(VIDEOEXT): Nucleus_Dmitriev_Lecture03.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture03.1-18-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture03.2-18-09-2014.MTS.$(VIDEOEXT)  Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 03","NSU 2014")

Nucleus_Dmitriev_Lecture04.$(VIDEOEXT): Nucleus_Dmitriev_Lecture04.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture04.1-25-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture04.2-25-09-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 04","NSU 2014")

Nucleus_Dmitriev_Lecture05.$(VIDEOEXT): Nucleus_Dmitriev_Lecture05.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture05.1-02-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture05.2-02-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 05","NSU 2014")

Nucleus_Dmitriev_Lecture06.$(VIDEOEXT): Nucleus_Dmitriev_Lecture06.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture06.1-09-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture06.2-09-10-2014.MTS.$(VIDEOEXT)  Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 06","NSU 2014")

Nucleus_Dmitriev_Lecture07.$(VIDEOEXT): Nucleus_Dmitriev_Lecture07.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture07.1-16-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture07.2-16-10-2014.MTS.$(VIDEOEXT)  Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 07","NSU 2014")

Nucleus_Dmitriev_Lecture08.$(VIDEOEXT): Nucleus_Dmitriev_Lecture08.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture08.1-23-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture08.2-23-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 08","NSU 2014")

Nucleus_Dmitriev_Lecture09.$(VIDEOEXT): Nucleus_Dmitriev_Lecture09.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture09.1-30-10-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture09.2-30-10-2014.MTS.$(VIDEOEXT)  Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 09","NSU 2014")

Nucleus_Dmitriev_Lecture10.$(VIDEOEXT): Nucleus_Dmitriev_Lecture10.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture10.1-06-11-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture10.2-06-11-2014.MTS.$(VIDEOEXT)  Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 10","NSU 2014")

Nucleus_Dmitriev_Lecture11.$(VIDEOEXT): Nucleus_Dmitriev_Lecture11.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture11.1-05-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture11.2-05-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 11","NSU 2014")

Nucleus_Dmitriev_Lecture12.$(VIDEOEXT): Nucleus_Dmitriev_Lecture12.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture12.1-05-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture12.2-05-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture12.3-05-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 12","NSU 2014")

Nucleus_Dmitriev_Lecture13.$(VIDEOEXT): Nucleus_Dmitriev_Lecture13.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture13.1-11-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture13.2-11-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 13","NSU 2014")

Nucleus_Dmitriev_Lecture14.$(VIDEOEXT): Nucleus_Dmitriev_Lecture14.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture14.1-12-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture14.2-12-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 14","NSU 2014")

Nucleus_Dmitriev_Lecture15.$(VIDEOEXT): Nucleus_Dmitriev_Lecture15.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture15.1-18-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture15.2-18-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 15","NSU 2014")

Nucleus_Dmitriev_Lecture16.$(VIDEOEXT): Nucleus_Dmitriev_Lecture16.png.$(VIDEOEXT) Nucleus_Dmitriev_Lecture16.1-25-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture16.2-25-12-2014.MTS.$(VIDEOEXT) Nucleus_Dmitriev_Lecture_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"Nuclear physics Dmitriev V.F. Lecture N 16","NSU 2014")

# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

