#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


QED_Reznichenko_Seminar01.$(VIDEOEXT): QED_Reznichenko_Seminar01-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar01-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_01.1-08.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_01.2-08.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_01.3-08.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 01","NSU 2015")


QED_Reznichenko_Seminar02.$(VIDEOEXT): QED_Reznichenko_Seminar02-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar02-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_02.1-15.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_02.2-15.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_02.3-15.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 02","NSU 2015")

QED_Reznichenko_Seminar03.$(VIDEOEXT): QED_Reznichenko_Seminar03-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar03-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_03.1-22.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_03.2-22.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_03.3-22.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 03","NSU 2015")

QED_Reznichenko_Seminar04.$(VIDEOEXT): QED_Reznichenko_Seminar04-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar04-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_04.1-29.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_04.2-29.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_04.3-29.09.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 04","NSU 2015")

QED_Reznichenko_Seminar05.$(VIDEOEXT): QED_Reznichenko_Seminar05-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar05-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_05.1-06.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_05.2-06.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 05","NSU 2015")

QED_Reznichenko_Seminar06.$(VIDEOEXT): QED_Reznichenko_Seminar06-1.png.$(VIDEOEXT)  QED_Reznichenko_Seminar06-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_06.1-13.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_06.2-13.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 06","NSU 2015")

QED_Reznichenko_Seminar07.$(VIDEOEXT): QED_Reznichenko_Seminar07-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar07-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_07.1-20.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_07.2-20.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 07","NSU 2015")

QED_Reznichenko_Seminar08.$(VIDEOEXT): QED_Reznichenko_Seminar08-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar08-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_08.1-27.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_08.2-27.10.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 08","NSU 2015")

QED_Reznichenko_Seminar09.$(VIDEOEXT): QED_Reznichenko_Seminar09-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar09-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_09.1-03.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_09.2-03.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 09","NSU 2015")

QED_Reznichenko_Seminar10.$(VIDEOEXT): QED_Reznichenko_Seminar10-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar10-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_10.1-10.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_10.2-10.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_10.3-10.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 10","NSU 2015")

QED_Reznichenko_Seminar11.$(VIDEOEXT): QED_Reznichenko_Seminar11-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar11-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_11.1-17.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_11.2-17.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 11","NSU 2015")

QED_Reznichenko_Seminar12.$(VIDEOEXT): QED_Reznichenko_Seminar12-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar12-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_12.1-24.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_12.2-24.11.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 12","NSU 2015")

QED_Reznichenko_Seminar13.$(VIDEOEXT): QED_Reznichenko_Seminar13-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar13-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_13.1-01.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_13.2-01.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 13","NSU 2015")

QED_Reznichenko_Seminar14.$(VIDEOEXT): QED_Reznichenko_Seminar14-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar14-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_14.1-08.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_14.2-08.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 14","NSU 2015")

QED_Reznichenko_Seminar15.$(VIDEOEXT): QED_Reznichenko_Seminar15-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar15-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_15.1-11.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_15.2-11.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 15","NSU 2015")

QED_Reznichenko_Seminar16.$(VIDEOEXT): QED_Reznichenko_Seminar16-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar16-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_16.1-15.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_16.2-15.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 16","NSU 2015")

QED_Reznichenko_Seminar17.$(VIDEOEXT): QED_Reznichenko_Seminar17-1.png.$(VIDEOEXT) QED_Reznichenko_Seminar17-2.png.$(VIDEOEXT) QED_Reznichenko_Seminar_17.1-22.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_17.2-22.12.15.MTS.$(VIDEOEXT) QED_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Reznichenko A.V. Seminar N 17","NSU 2015")



# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

