#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


QCD_Reznichenko_Seminar01.$(VIDEOEXT): QCD_Reznichenko_Seminar01.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.1-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.2-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.3-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.4-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 01","NSU 2015")


QCD_Reznichenko_Seminar02.$(VIDEOEXT): QCD_Reznichenko_Seminar02.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.1-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.2-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.3-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.4-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 02","NSU 2015")

QCD_Reznichenko_Seminar03.$(VIDEOEXT): QCD_Reznichenko_Seminar03.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_03.1-24.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_03.2-24.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_03.3-24.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 03","NSU 2015")

QCD_Reznichenko_Seminar04.$(VIDEOEXT): QCD_Reznichenko_Seminar04.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_04.1-03.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_04.2-03.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_04.3-03.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 04","NSU 2015")


QCD_Reznichenko_Seminar05.$(VIDEOEXT): QCD_Reznichenko_Seminar05.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_05.1-10.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_05.2-10.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_05.3-10.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 05","NSU 2015")

QCD_Reznichenko_Seminar06.$(VIDEOEXT): QCD_Reznichenko_Seminar06.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.1-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.2-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.3-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.4-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 06","NSU 2015")

QCD_Reznichenko_Seminar07.$(VIDEOEXT): QCD_Reznichenko_Seminar07.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_07.1-19.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_07.2-19.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_07.3-19.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 07","NSU 2015")

QCD_Reznichenko_Seminar08.$(VIDEOEXT): QCD_Reznichenko_Seminar08.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.1-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.2-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.3-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.4-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 08","NSU 2015")

QCD_Reznichenko_Seminar09.$(VIDEOEXT): QCD_Reznichenko_Seminar09.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.1-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.2-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.3-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.4-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 09","NSU 2015")

QCD_Reznichenko_Seminar10.$(VIDEOEXT): QCD_Reznichenko_Seminar10.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.1-06.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.2-06.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.3-06.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.4-06.04.15.MTS.$(VIDEOEXT)  QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 10","NSU 2015")

QCD_Reznichenko_Seminar11.$(VIDEOEXT): QCD_Reznichenko_Seminar11.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_11.1-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_11.2-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 11","NSU 2015")

QCD_Reznichenko_Seminar12.$(VIDEOEXT): QCD_Reznichenko_Seminar12.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_12.1-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_12.2-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_12.3-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 12","NSU 2015")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

