#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


QCD_Reznichenko_Seminar01.$(VIDEOEXT): QCD_Reznichenko_Seminar01.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.1-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.2-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.3-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_01.4-10.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 01","NSU 2015")


QCD_Reznichenko_Seminar02.$(VIDEOEXT): QCD_Reznichenko_Seminar02.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.1-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.2-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.3-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_02.4-17.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 02","NSU 2015")

QCD_Reznichenko_Seminar03.$(VIDEOEXT): QCD_Reznichenko_Seminar03.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_03.1-24.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_03.2-24.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_03.3-24.02.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 03","NSU 2015")

QCD_Reznichenko_Seminar04.$(VIDEOEXT): QCD_Reznichenko_Seminar04.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_04.1-03.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_04.2-03.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_04.3-03.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 04","NSU 2015")


QCD_Reznichenko_Seminar05.$(VIDEOEXT): QCD_Reznichenko_Seminar05.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_05.1-10.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_05.2-10.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_05.3-10.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 05","NSU 2015")

QCD_Reznichenko_Seminar06.$(VIDEOEXT): QCD_Reznichenko_Seminar06.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.1-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.2-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.3-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_06.4-17.03.15.mts.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 06","NSU 2015")

QCD_Reznichenko_Seminar07.$(VIDEOEXT): QCD_Reznichenko_Seminar07.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_07.1-19.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_07.2-19.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_07.3-19.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 07","NSU 2015")

QCD_Reznichenko_Seminar08.$(VIDEOEXT): QCD_Reznichenko_Seminar08.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.1-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.2-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.3-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_08.4-24.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 08","NSU 2015")

QCD_Reznichenko_Seminar09.$(VIDEOEXT): QCD_Reznichenko_Seminar09.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.1-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.2-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.3-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_09.4-31.03.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 09","NSU 2015")

QCD_Reznichenko_Seminar10.$(VIDEOEXT): QCD_Reznichenko_Seminar10.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.1-06.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.2-06.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.3-06.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_10.4-06.04.15.MTS.$(VIDEOEXT)  QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 10","NSU 2015")

QCD_Reznichenko_Seminar11.$(VIDEOEXT): QCD_Reznichenko_Seminar11.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_11.1-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_11.2-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 11","NSU 2015")

QCD_Reznichenko_Seminar12.$(VIDEOEXT): QCD_Reznichenko_Seminar12.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_12.1-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_12.2-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_12.3-07.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 12","NSU 2015")

QCD_Reznichenko_Seminar13.$(VIDEOEXT): QCD_Reznichenko_Seminar13.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_13.1-27.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_13.2-27.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_13.3-27.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 13","NSU 2015")

QCD_Reznichenko_Seminar14.$(VIDEOEXT): QCD_Reznichenko_Seminar14.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_14.1-28.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_14.2-28.04.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 14","NSU 2015")

QCD_Reznichenko_Seminar15.$(VIDEOEXT): QCD_Reznichenko_Seminar15.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_15.1-05.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_15.2-05.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_15.3-05.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 15","NSU 2015")

QCD_Reznichenko_Seminar16.$(VIDEOEXT): QCD_Reznichenko_Seminar16.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_16.1-06.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_16.2-06.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_16.3-06.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 16","NSU 2015")

QCD_Reznichenko_Seminar17.$(VIDEOEXT): QCD_Reznichenko_Seminar17.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_17.1-12.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_17.2-12.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_17.3-12.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 17","NSU 2015")

QCD_Reznichenko_Seminar18.$(VIDEOEXT): QCD_Reznichenko_Seminar18.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_18.1-15.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_18.2-15.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_18.3-15.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 18","NSU 2015")

QCD_Reznichenko_Seminar19.$(VIDEOEXT): QCD_Reznichenko_Seminar19.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_19.1-19.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_19.2-19.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_19.3-19.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 19","NSU 2015")

QCD_Reznichenko_Seminar20.$(VIDEOEXT): QCD_Reznichenko_Seminar20.png.$(VIDEOEXT) QCD_Reznichenko_Seminar_20.1-22.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_20.2-22.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_20.3-22.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_20.4-22.05.15.MTS.$(VIDEOEXT) QCD_Reznichenko_Seminar_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"QCD Reznichenko A.V. Seminar N 20","NSU 2015")

# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

