#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"

# Lectures 2022

GR_Grabovsky_Lecture01.$(VIDEOEXT): GR_Grabovsky_Lecture01.png.$(VIDEOEXT) Grabovsky-GR-1-1-3.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-1-2-3.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 01","NSU 2022")

GR_Grabovsky_Lecture02.$(VIDEOEXT): GR_Grabovsky_Lecture02.png.$(VIDEOEXT) Grabovsky-GR-2-1-10.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-2-2-10.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 02","NSU 2022")

GR_Grabovsky_Lecture03.$(VIDEOEXT): GR_Grabovsky_Lecture03.png.$(VIDEOEXT) Grabovsky-GR-3-1-17.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-3-2-17.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 03","NSU 2022")

GR_Grabovsky_Lecture04.$(VIDEOEXT): GR_Grabovsky_Lecture04.png.$(VIDEOEXT) Grabovsky-GR-4-1-24.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-4-2-24.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 04","NSU 2022")

GR_Grabovsky_Lecture05.$(VIDEOEXT): GR_Grabovsky_Lecture05.png.$(VIDEOEXT) Grabovsky-GR-5-1-1.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-5-2-1.10.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 05","NSU 2022")

GR_Grabovsky_Lecture06.$(VIDEOEXT): GR_Grabovsky_Lecture06.png.$(VIDEOEXT) Grabovsky-GR-6-1-8.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-6-2-8.10.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 06","NSU 2022")

GR_Grabovsky_Lecture07.$(VIDEOEXT): GR_Grabovsky_Lecture07.png.$(VIDEOEXT) Grabovsky-GR-7-1-15.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-7-2-15.10.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 07","NSU 2022")

GR_Grabovsky_Lecture08.$(VIDEOEXT): GR_Grabovsky_Lecture08.png.$(VIDEOEXT) Grabovsky-GR-8-1-22.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-8-2-22.10.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 08","NSU 2022")

GR_Grabovsky_Lecture09.$(VIDEOEXT): GR_Grabovsky_Lecture09.png.$(VIDEOEXT) Grabovsky-GR-9-1-29.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-9-2-29.10.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 09","NSU 2022")

GR_Grabovsky_Lecture10.$(VIDEOEXT): GR_Grabovsky_Lecture10.png.$(VIDEOEXT) GR_Grabovsky_Lecture10-summery.png.$(VIDEOEXT) Grabovsky-GR-10-1-5.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-10-2-5.11.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 10","NSU 2022")

GR_Grabovsky_Lecture11.$(VIDEOEXT): GR_Grabovsky_Lecture11.png.$(VIDEOEXT) Grabovsky-GR-11-1-12.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-11-2-12.11.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 11","NSU 2022")


GR_Grabovsky_Lecture12.$(VIDEOEXT): GR_Grabovsky_Lecture12.png.$(VIDEOEXT) Grabovsky-GR-12-1-19.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-12-2-19.11.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 12","NSU 2022")


GR_Grabovsky_Lecture13.$(VIDEOEXT): GR_Grabovsky_Lecture13.png.$(VIDEOEXT) Grabovsky-GR-13-1-26.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-13-2-26.11.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 13","NSU 2022")

GR_Grabovsky_Lecture14.$(VIDEOEXT): GR_Grabovsky_Lecture14.png.$(VIDEOEXT) Grabovsky-GR-14-1-3.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-14-2-3.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 14","NSU 2022")

GR_Grabovsky_Lecture15.$(VIDEOEXT): GR_Grabovsky_Lecture15.png.$(VIDEOEXT) Grabovsky-GR-15-1-14.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-15-2-14.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 15","NSU 2022")

GR_Grabovsky_Lecture16.$(VIDEOEXT): GR_Grabovsky_Lecture16.png.$(VIDEOEXT) Grabovsky-GR-16-1-17.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-16-2-17.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 16","NSU 2022")

GR_Grabovsky_Lecture17.$(VIDEOEXT): GR_Grabovsky_Lecture17.png.$(VIDEOEXT) Grabovsky-GR-17-1-24.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-17-2-24.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Lecture N 17","NSU 2022")

#Seminars 2022

GR_Grabovsky_Seminar01.$(VIDEOEXT): GR_Grabovsky_Seminar01.png.$(VIDEOEXT) GR_Grabovsky_Problem01.png.$(VIDEOEXT) Grabovsky-GR-1-3-3.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-1-4-3.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 01","NSU 2022")

GR_Grabovsky_Seminar02.$(VIDEOEXT): GR_Grabovsky_Seminar02.png.$(VIDEOEXT) GR_Grabovsky_Problem02.png.$(VIDEOEXT) Grabovsky-GR-2-3-10.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-2-4-10.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 02","NSU 2022")

GR_Grabovsky_Seminar03.$(VIDEOEXT): GR_Grabovsky_Seminar03.png.$(VIDEOEXT) GR_Grabovsky_Problem03.png.$(VIDEOEXT) Grabovsky-GR-3-3-17.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-3-4-17.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 03","NSU 2022")

GR_Grabovsky_Seminar04.$(VIDEOEXT): GR_Grabovsky_Seminar04.png.$(VIDEOEXT) GR_Grabovsky_Problem04.png.$(VIDEOEXT) Grabovsky-GR-4-3-24.9.22.MTS.$(VIDEOEXT) Grabovsky-GR-4-4-24.9.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 04","NSU 2022")

GR_Grabovsky_Seminar05.$(VIDEOEXT): GR_Grabovsky_Seminar05.png.$(VIDEOEXT) GR_Grabovsky_Problem05.png.$(VIDEOEXT) Grabovsky-GR-5-3-1.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-5-4-1.10.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 05","NSU 2022")

GR_Grabovsky_Seminar06.$(VIDEOEXT): GR_Grabovsky_Seminar06.png.$(VIDEOEXT) GR_Grabovsky_Problem06.png.$(VIDEOEXT) Grabovsky-GR-6-3-8.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-6-4-8.10.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 06","NSU 2022")

GR_Grabovsky_Seminar07.$(VIDEOEXT): GR_Grabovsky_Seminar07.png.$(VIDEOEXT) GR_Grabovsky_Seminar07-summery.png.$(VIDEOEXT) GR_Grabovsky_Problem07.png.$(VIDEOEXT) Grabovsky-GR-7-3-15.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-7-4-15.10.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 07","NSU 2022")

GR_Grabovsky_Seminar08.$(VIDEOEXT): GR_Grabovsky_Seminar08.png.$(VIDEOEXT) GR_Grabovsky_Seminar08-summery.png.$(VIDEOEXT) GR_Grabovsky_Problem08.png.$(VIDEOEXT) Grabovsky-GR-8-3-22.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-8-4-22.10.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 08","NSU 2022")

GR_Grabovsky_Seminar09.$(VIDEOEXT): GR_Grabovsky_Seminar09.png.$(VIDEOEXT) GR_Grabovsky_Problem09.png.$(VIDEOEXT) Grabovsky-GR-9-3-29.10.22.MTS.$(VIDEOEXT) Grabovsky-GR-9-4-29.10.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 09","NSU 2022")

GR_Grabovsky_Seminar10.$(VIDEOEXT): GR_Grabovsky_Seminar10.png.$(VIDEOEXT) GR_Grabovsky_Problem10.png.$(VIDEOEXT) Grabovsky-GR-10-3-5.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-10-4-5.11.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 10","NSU 2022")

GR_Grabovsky_Seminar11.$(VIDEOEXT): GR_Grabovsky_Seminar11.png.$(VIDEOEXT) GR_Grabovsky_Problem11.png.$(VIDEOEXT) Grabovsky-GR-11-3-12.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-11-4-12.11.22.MTS.$(VIDEOEXT)  GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 11","NSU 2022")

GR_Grabovsky_Seminar12.$(VIDEOEXT): GR_Grabovsky_Seminar12.png.$(VIDEOEXT) GR_Grabovsky_Problem12.png.$(VIDEOEXT) Grabovsky-GR-12-3-19.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-12-4-19.11.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 12","NSU 2022")

GR_Grabovsky_Seminar13.$(VIDEOEXT): GR_Grabovsky_Seminar13.png.$(VIDEOEXT) GR_Grabovsky_Problem13.png.$(VIDEOEXT) Grabovsky-GR-13-3-26.11.22.MTS.$(VIDEOEXT) Grabovsky-GR-13-4-26.11.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 13","NSU 2022")

GR_Grabovsky_Seminar14.$(VIDEOEXT): GR_Grabovsky_Seminar14.png.$(VIDEOEXT) GR_Grabovsky_Problem14.png.$(VIDEOEXT) Grabovsky-GR-14-3-3.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-14-4-3.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 14","NSU 2022")

GR_Grabovsky_Seminar15.$(VIDEOEXT): GR_Grabovsky_Seminar15.png.$(VIDEOEXT) GR_Grabovsky_Problem15.png.$(VIDEOEXT) Grabovsky-GR-15-3-14.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-15-4-14.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 15","NSU 2022")

GR_Grabovsky_Seminar16.$(VIDEOEXT): GR_Grabovsky_Seminar16.png.$(VIDEOEXT) GR_Grabovsky_Problem16.png.$(VIDEOEXT) Grabovsky-GR-16-3-17.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-16-4-17.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 16","NSU 2022")

GR_Grabovsky_Seminar17.$(VIDEOEXT): GR_Grabovsky_Seminar17.png.$(VIDEOEXT) GR_Grabovsky_Problem17.png.$(VIDEOEXT) Grabovsky-GR-17-3-24.12.22.MTS.$(VIDEOEXT) Grabovsky-GR-17-4-24.12.22.MTS.$(VIDEOEXT) GR_Grabovsky_afterwords.png.$(VIDEOEXT)
	$(call MERGE,$^,"General relativity Andrei Grabovsky Seminar N 17","NSU 2022")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

