#
# Сборка лекций
# 

include ../rules.mk

all:
	@echo "Usage: make file.$(VIDEOEXT)"
	@echo "Usage: make clean"
	@echo "Usage: make fullclean"


QED_Fadin_Lecture01.$(VIDEOEXT): QED_Fadin_Lecture01-1.png.$(VIDEOEXT) QED_Fadin_Lecture01-2.png.$(VIDEOEXT)  QED_Fadin_Lecture01.1_3.9.2013.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 01","NSU 2013")

QED_Fadin_Lecture02.$(VIDEOEXT): QED_Fadin_Lecture02-1.png.$(VIDEOEXT) QED_Fadin_Lecture02-2.png.$(VIDEOEXT)  QED_Fadin_Lecture02.1_3.9.2013.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 02","NSU 2013")

QED_Fadin_Lecture03.$(VIDEOEXT): QED_Fadin_Lecture03-1.png.$(VIDEOEXT) QED_Fadin_Lecture03-2.png.$(VIDEOEXT)  QED_Fadin_Lecture03.1_11.9.2013.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 03","NSU 2013")

QED_Fadin_Lecture04.$(VIDEOEXT): QED_Fadin_Lecture04-1.png.$(VIDEOEXT) QED_Fadin_Lecture04-2.png.$(VIDEOEXT)  QED_Fadin_Lecture04.1_11.9.2013.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 04","NSU 2013")

QED_Fadin_Lecture05.$(VIDEOEXT): QED_Fadin_Lecture05-1.png.$(VIDEOEXT) QED_Fadin_Lecture05-2.png.$(VIDEOEXT)  QED_Fadin_Lecture05.1_17.9.2013.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 05","NSU 2013")

QED_Fadin_Lecture06.$(VIDEOEXT): QED_Fadin_Lecture06-1.png.$(VIDEOEXT) QED_Fadin_Lecture06-2.png.$(VIDEOEXT)  QED_Fadin_Lecture06.1_17.9.2013.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 06","NSU 2013")

QED_Fadin_Lecture07.$(VIDEOEXT): QED_Fadin_Lecture07-1.png.$(VIDEOEXT) QED_Fadin_Lecture07-2.png.$(VIDEOEXT)  QED_Fadin_Lecture07.1_01.10.2013.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 07","NSU 2013")

QED_Fadin_Lecture08.$(VIDEOEXT): QED_Fadin_Lecture08-1.png.$(VIDEOEXT) QED_Fadin_Lecture08-2.png.$(VIDEOEXT)  QED_Fadin_Lecture08.1_01.10.2013.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 08","NSU 2013")

QED_Fadin_Lecture09.$(VIDEOEXT): QED_Fadin_Lecture09-1.png.$(VIDEOEXT) QED_Fadin_Lecture09-2.png.$(VIDEOEXT)  QED_Fadin_Lecture09.1_19.11.13.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 09","NSU 2013")

QED_Fadin_Lecture10.$(VIDEOEXT): QED_Fadin_Lecture10-1.png.$(VIDEOEXT) QED_Fadin_Lecture10-2.png.$(VIDEOEXT)  QED_Fadin_Lecture10.1_26.11.13.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 10","NSU 2013")

QED_Fadin_Lecture11.$(VIDEOEXT): QED_Fadin_Lecture11-1.png.$(VIDEOEXT) QED_Fadin_Lecture11-2.png.$(VIDEOEXT)  QED_Fadin_Lecture11.1_26.11.13.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 11","NSU 2013")

QED_Fadin_Lecture12.$(VIDEOEXT): QED_Fadin_Lecture12-1.png.$(VIDEOEXT) QED_Fadin_Lecture12-2.png.$(VIDEOEXT)  QED_Fadin_Lecture12.1_03.12.13.mts.$(VIDEOEXT) QED_Fadin_Lecture12.2_03.12.13.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 12","NSU 2013")

QED_Fadin_Lecture13.$(VIDEOEXT): QED_Fadin_Lecture13-1.png.$(VIDEOEXT) QED_Fadin_Lecture13-2.png.$(VIDEOEXT)  QED_Fadin_Lecture13.1_10.12.13.mts.$(VIDEOEXT) QED_Fadin_Lecture13.2_10.12.13.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 13","NSU 2013")

QED_Fadin_Lecture14.$(VIDEOEXT): QED_Fadin_Lecture14-1.png.$(VIDEOEXT) QED_Fadin_Lecture14-2.png.$(VIDEOEXT)  QED_Fadin_Lecture14.1_17.12.13.mts.$(VIDEOEXT)  QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 14","NSU 2013")

QED_Fadin_Lecture15.$(VIDEOEXT): QED_Fadin_Lecture15-1.png.$(VIDEOEXT) QED_Fadin_Lecture15-2.png.$(VIDEOEXT)  QED_Fadin_Lecture15.1_17.12.13.mts.$(VIDEOEXT) QED_Fadin_Lecture_afterwords-1.png.$(VIDEOEXT)
	$(call MERGE,$^,"QED Fadin V.S. Lecture N 15","NSU 2013")


# Чистка
clean:
	rm -f *.*.$(VIDEOEXT)  *~
# Полная чистка
fullclean: clean
	rm -f *.$(VIDEOEXT)

